---
  env:
    browser: true
    node: true
  globals:
    Uint8Array: true
    DataView: true
    Buffer: true
    TextDecoder: true
  parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
      scriptType: "module"
  extends: "semistandard"
  rules:
    indent: [error, 4]

