language: node_js
sudo: false
install:
  - npm install -g codecov
  - yarn install
cache:
  directories:
    - node_modules
node_js:
  - "node"
  - "lts/*"
  - "8"

script:
  - yarn lint
  - yarn test
after_success:
  - codecov
